Merge proto files from multiprocess run into one file.
ROCm/rocprofiler-systems pull request #63
Opened 2024-12-16 14:04 UTC by pranswarup

- Execute the merge multiprocess script from the rank 0 process
- Added scripts folder to path, when setup-env is added to the path
- Install merge_multiprocess_output.sh to /share/rocprofiler-systems/bin dir in the install dir
- Added script to merge multiprocess output to one file when there are multiprocess proto files written

2024-12-16 19:48 UTC, dgaliffiAMD commented on cmake/Templates/setup-env.sh.in
> +PATH=${BASEDIR}/share/rocprofiler-systems/bin:${PATH}
```suggestion
PATH=${BASEDIR}/@CMAKE_INSTALL_DATAROOTDIR@/@PROJECT_NAME@/bin:${PATH}
```
This is a template file, so please use the appropriate variables. If there is ever a change to the PROJECT_NAME (again), then this will automatically handle that.

2024-12-16 19:48 UTC, dgaliffiAMD commented on CMakeLists.txt
> +    ${PROJECT_BINARY_DIR}/${CMAKE_INSTALL_DATAROOTDIR}/${PROJECT_NAME}/merge_multiprocess_output.sh COPYONLY)
```suggestion
    ${PROJECT_BINARY_DIR}/${CMAKE_INSTALL_DATAROOTDIR}/${PROJECT_NAME}/bin/merge_multiprocess_output.sh COPYONLY)
```
Making the staging folder match the destination folder.

2024-12-16 19:48 UTC, dgaliffiAMD commented on CMakeLists.txt
> +    PROGRAMS ${PROJECT_BINARY_DIR}/${CMAKE_INSTALL_DATAROOTDIR}/${PROJECT_NAME}/merge_multiprocess_output.sh
```suggestion
    PROGRAMS ${PROJECT_BINARY_DIR}/${CMAKE_INSTALL_DATAROOTDIR}/${PROJECT_NAME}/bin/merge_multiprocess_output.sh
```

2024-12-16 19:48 UTC, dgaliffiAMD commented on cmake/Templates/setup-env.sh.in
`cmake/Templates/modulefile.in` will also need modification for this change

2024-12-18 16:31 UTC, dgaliffiAMD requested changes

2024-12-18 16:31 UTC, dgaliffiAMD commented on scripts/merge_multiprocess_output.sh
I suggest renaming this file to `merge-multiprocess-output.sh` (ie., dashes rather than underscores) to align with the formatting of the other files.

2024-12-18 16:31 UTC, dgaliffiAMD commented on CMakeLists.txt
> +    ${PROJECT_BINARY_DIR}/${CMAKE_INSTALL_DATAROOTDIR}/${PROJECT_NAME}/bin/merge_multiprocess_output.sh
```suggestion
    ${PROJECT_SOURCE_DIR}/scripts/merge-multiprocess-output.sh
    ${PROJECT_BINARY_DIR}/${CMAKE_INSTALL_DATAROOTDIR}/${PROJECT_NAME}/bin/merge-multiprocess-output.sh
```
Updating to account for renaming.

2024-12-18 16:31 UTC, dgaliffiAMD commented on CMakeLists.txt
> +        ${PROJECT_BINARY_DIR}/${CMAKE_INSTALL_DATAROOTDIR}/${PROJECT_NAME}/bin/merge_multiprocess_output.sh
```suggestion
        ${PROJECT_BINARY_DIR}/${CMAKE_INSTALL_DATAROOTDIR}/${PROJECT_NAME}/bin/merge-multiprocess-output.sh
```
Updating to account for name change

2024-12-18 16:31 UTC, dgaliffiAMD commented on source/lib/core/perfetto.cpp
> +                "merge_multiprocess_output.sh '" + std::string(folder_path) + "'";
```suggestion
                "merge-multiprocess-output.sh '" + std::string(folder_path) + "'";
```
Updated to account for name change.

2024-12-18 16:31 UTC, dgaliffiAMD commented on source/lib/core/perfetto.cpp
> +                                   "Failed to execute merge_multiprocess_output.sh with "
```suggestion
                                   "Failed to execute merge-multiprocess-output.sh with "
```

2024-12-18 16:31 UTC, dgaliffiAMD commented on source/lib/core/perfetto.cpp
> +            const char* file_path   = _filename.c_str();
You can use a Timemory function to find the basename of the file.
See here as an example: https://github.com/ROCm/rocprofiler-systems/blob/b6a52cd9b4a98539a6e30553ffdc98558091f82a/source/bin/rocprof-sys-instrument/module_function.cpp#L430-L432

    auto _basename = [](std::string_view _v) {
        return std::string{ tim::filepath::basename(_v) };
    };

2024-12-18 16:31 UTC, dgaliffiAMD commented on scripts/merge_multiprocess_output.sh
> +done
```suggestion
TIMEOUT=60  # Timeout in seconds
for file in "${PROTO_FILES[@]}"; do
  SECONDS=0
  while lsof "$file" > /dev/null 2>&1; do
    if [ $SECONDS -ge $TIMEOUT ]; then
      echo "Timeout reached while waiting for $file to be released."
      break
    fi
    echo "Waiting for $file to be released..."
    sleep 1
  done
done
```
Consider adding a timeout to avoid a possible infinite loop.

2024-12-18 16:31 UTC, dgaliffiAMD commented on scripts/merge_multiprocess_output.sh
> +echo "All multiprocess .proto files in '$FOLDER_PATH' have been merged into '$OUTPUT_FILE'."
```suggestion
echo "All multiprocess .proto files in '$FOLDER_PATH' have been merged into '$OUTPUT_FILE'."

```
Just formatting. Ending on a blank line.

2024-12-18 19:14 UTC, dgaliffiAMD commented on source/lib/core/perfetto.cpp
> +            const char* file_path   = _filename.c_str();
Sorry. I misread. Try: `tim::filepath::dirname` rather than basename.

2024-12-18 20:08 UTC, pranswarup commented on scripts/merge_multiprocess_output.sh
The script has been renamed to merge-multiprocess-output.sh

2024-12-18 22:01 UTC, dgaliffiAMD approved these changes

2024-12-18 22:34 UTC, merged